// <auto-generated />
using System;
using Garage2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Garage2._0.Migrations
{
    [DbContext(typeof(Garage2_0Context))]
    [Migration("20210823181752_AddedMoreTestData")]
    partial class AddedMoreTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garage2._0.Models.Entities.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2021, 8, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Gold",
                            Make = "BMW",
                            Model = "525i",
                            NoOfWheels = 4,
                            RegNo = "CAR123",
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2021, 8, 20, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Color = "White",
                            Make = "Volvo",
                            Model = "S90 T5",
                            NoOfWheels = 4,
                            RegNo = "CAR456",
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2021, 8, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Make = "Audi",
                            Model = "RS7",
                            NoOfWheels = 4,
                            RegNo = "CAR789",
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2021, 8, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Red",
                            Make = "Mercedes-Benz",
                            Model = "Traveller",
                            NoOfWheels = 6,
                            RegNo = "BUS123",
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2021, 8, 21, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Blue",
                            Make = "Scania",
                            Model = "SL Edition",
                            NoOfWheels = 6,
                            RegNo = "BUS456",
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2021, 8, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Grey",
                            Make = "DAF",
                            Model = "Long Cruiser",
                            NoOfWheels = 6,
                            RegNo = "TRU123",
                            VehicleType = 6
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2021, 8, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Black",
                            Make = "Scania",
                            Model = "Heavy Loader",
                            NoOfWheels = 8,
                            RegNo = "TRU456",
                            VehicleType = 6
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2021, 8, 23, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Green",
                            Make = "Yamaha",
                            Model = "F1",
                            NoOfWheels = 2,
                            RegNo = "MCL123",
                            VehicleType = 5
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new DateTime(2021, 8, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Color = "Silver",
                            Make = "BMX",
                            Model = "Biker",
                            NoOfWheels = 2,
                            RegNo = "BCL123",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new DateTime(2021, 8, 23, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            Color = "White",
                            Make = "Boeing",
                            Model = "Exclusive Air",
                            NoOfWheels = 3,
                            RegNo = "AIR123",
                            VehicleType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
