// <auto-generated />
using System;
using Garage2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Garage2._0.Migrations
{
    [DbContext(typeof(Garage2_0Context))]
    partial class Garage2_0ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garage2._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfWheels")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfWheels = 4,
                            ArrivalTime = new DateTime(2021, 8, 19, 13, 38, 23, 84, DateTimeKind.Local).AddTicks(6545),
                            Color = "Red",
                            Make = "BMW",
                            Model = "C5",
                            RegNo = "ABC123",
                            vehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            AmountOfWheels = 4,
                            ArrivalTime = new DateTime(2021, 8, 19, 13, 38, 23, 86, DateTimeKind.Local).AddTicks(8101),
                            Color = "White",
                            Make = "Volvo",
                            Model = "Z7",
                            RegNo = "EFG124",
                            vehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            AmountOfWheels = 4,
                            ArrivalTime = new DateTime(2021, 8, 19, 13, 38, 23, 86, DateTimeKind.Local).AddTicks(8148),
                            Color = "Black",
                            Make = "Audi",
                            Model = "M09",
                            RegNo = "GHY125",
                            vehicleType = 0
                        },
                        new
                        {
                            Id = 4,
                            AmountOfWheels = 4,
                            ArrivalTime = new DateTime(2021, 8, 19, 13, 38, 23, 86, DateTimeKind.Local).AddTicks(8153),
                            Color = "Red",
                            Make = "BMW",
                            Model = "FF5",
                            RegNo = "LKJ126",
                            vehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            AmountOfWheels = 12,
                            ArrivalTime = new DateTime(2021, 8, 19, 13, 38, 23, 86, DateTimeKind.Local).AddTicks(8157),
                            Color = "Yellow",
                            Make = "BMW",
                            Model = "C95",
                            RegNo = "OPR127",
                            vehicleType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
